package productmanagement;

import java.awt.Image;
import java.nio.file.Paths;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class ProductCatalogueFourItemTemplate extends javax.swing.JPanel {
    ArrayList<ProductItem> items = new ArrayList<>();

    public ProductCatalogueFourItemTemplate(String[] itemIds) {
        initComponents();
        
        // Get first four Items
        for (int i = 0; i < 4; i++) {
            boolean found = false;
            ArrayList<String> itemArray = ReadObject.readArray(ProductItem.FILE_NAME);
            // Iterate through the Item array
            for (String itemDetails : itemArray) {
                // Split the line into details
                String[] details = itemDetails.split(";");
                // Check the details for a matching Id
                if (details[0].equalsIgnoreCase(itemIds[i])) {
                    // Create a Product Item object and add into array list
                    items.add(new ProductItem(details));
                    found = true;
                    break;
                }
            }
            // If item is not found, create an empty Product Item object and add it to the array list
            if (!found) {
                items.add(new ProductItem("", "", "", 0, "", "", "", "", ""));
            }
        }

        resetItem(items.get(0), lblImageItem1, lblNameItem1, lblBrandItem1, lblPriceItem1);
        resetItem(items.get(1), lblImageItem2, lblNameItem2, lblBrandItem2, lblPriceItem2);
        resetItem(items.get(2), lblImageItem3, lblNameItem3, lblBrandItem3, lblPriceItem3);
        resetItem(items.get(3), lblImageItem4, lblNameItem4, lblBrandItem4, lblPriceItem4);
    }

    private void resetItem(ProductItem item, JLabel lblImage, JLabel lblName, JLabel lblBrand, JLabel lblPrice) {
        if (!item.getItemId().trim().equalsIgnoreCase("")) {
            lblImage.setIcon(resizeImage(Paths.get("").toAbsolutePath().toString() + "/src" + item.getItemImagePath(), lblImage));
            lblName.setText(item.getItemName());
            lblBrand.setText(item.getItemBrand());
            lblPrice.setText("RM " + String.valueOf(item.getItemPrice()));
        } else {
            lblImage.setIcon(new ImageIcon());
            lblName.setText("Title");
            lblBrand.setText("Brand");
            lblPrice.setText("Price");
        }
        lblImage.setLocation(lblImage.getBounds().x, lblImage.getBounds().y);
    }
    
    // Create a method to resize the image and label
    private ImageIcon resizeImage(String imagePath, JLabel lblImage){
        int x, y;
        double width, height, ratio;
        width = lblImage.getPreferredSize().getWidth();
        height = lblImage.getPreferredSize().getHeight();

        // Get the imageicon and get the width & height of the image
        ImageIcon MyImage = new ImageIcon(imagePath);
        x = MyImage.getIconWidth();
        y = MyImage.getIconHeight();
        ratio = (double) x / y;
        
        // To differentiate if the image is wider or higher than the label
        if (ratio > (width / height)) {
            if (ratio >= 1) {
                lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y + (int) Math.round((height - (height / ratio)) / 2), (int) width, (int) Math.round(height / ratio));
            } else {
                lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y + (int) Math.round((height - (height * ratio)) / 2), (int) width, (int) Math.round(height * ratio));
            }
        } else if (ratio < (width / height)){
            if (ratio >= 1) {
                lblImage.setBounds(lblImage.getBounds().x + (int) Math.round((width - (height / ratio)) / 2), lblImage.getBounds().y, (int) Math.round(height / ratio), (int) height);
            } else {
                lblImage.setBounds(lblImage.getBounds().x + (int) Math.round((width - (height * ratio)) / 2), lblImage.getBounds().y, (int) Math.round(height * ratio), (int) height);
            }
        } else {
            // The width is equal to the height, then only scale the image
            lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y, (int) width, (int) height);
        }
        
        // Resize the image to the size of the label
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance((int) lblImage.getBounds().getWidth(),(int) lblImage.getBounds().getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem1 = new javax.swing.JPanel();
        lblImageItem1 = new javax.swing.JLabel();
        pnlContentItem1 = new javax.swing.JPanel();
        lblNameItem1 = new javax.swing.JLabel();
        lblBrandItem1 = new javax.swing.JLabel();
        lblPriceItem1 = new javax.swing.JLabel();
        pnlItem2 = new javax.swing.JPanel();
        lblImageItem2 = new javax.swing.JLabel();
        pnlContentItem2 = new javax.swing.JPanel();
        lblNameItem2 = new javax.swing.JLabel();
        lblBrandItem2 = new javax.swing.JLabel();
        lblPriceItem2 = new javax.swing.JLabel();
        pnlItem3 = new javax.swing.JPanel();
        lblImageItem3 = new javax.swing.JLabel();
        pnlContentItem3 = new javax.swing.JPanel();
        lblNameItem3 = new javax.swing.JLabel();
        lblBrandItem3 = new javax.swing.JLabel();
        lblPriceItem3 = new javax.swing.JLabel();
        pnlItem4 = new javax.swing.JPanel();
        lblImageItem4 = new javax.swing.JLabel();
        pnlContentItem4 = new javax.swing.JPanel();
        lblNameItem4 = new javax.swing.JLabel();
        lblBrandItem4 = new javax.swing.JLabel();
        lblPriceItem4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(420, 420));
        setMinimumSize(new java.awt.Dimension(420, 420));
        setPreferredSize(new java.awt.Dimension(420, 420));
        setLayout(null);

        pnlItem1.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem1.setMaximumSize(new java.awt.Dimension(210, 210));
        pnlItem1.setMinimumSize(new java.awt.Dimension(210, 210));
        pnlItem1.setPreferredSize(new java.awt.Dimension(210, 210));
        pnlItem1.setLayout(null);

        lblImageItem1.setMaximumSize(new java.awt.Dimension(210, 105));
        lblImageItem1.setMinimumSize(new java.awt.Dimension(210, 105));
        lblImageItem1.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlItem1.add(lblImageItem1);
        lblImageItem1.setBounds(0, 0, 210, 105);

        pnlContentItem1.setMaximumSize(new java.awt.Dimension(210, 105));
        pnlContentItem1.setMinimumSize(new java.awt.Dimension(210, 105));
        pnlContentItem1.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlContentItem1.setLayout(null);

        lblNameItem1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem1.setText("MR CHAIR");
        lblNameItem1.setMaximumSize(new java.awt.Dimension(210, 20));
        lblNameItem1.setMinimumSize(new java.awt.Dimension(210, 20));
        lblNameItem1.setPreferredSize(new java.awt.Dimension(210, 20));
        pnlContentItem1.add(lblNameItem1);
        lblNameItem1.setBounds(0, 11, 210, 20);

        lblBrandItem1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem1.setText("BRAND");
        lblBrandItem1.setMaximumSize(new java.awt.Dimension(210, 15));
        lblBrandItem1.setMinimumSize(new java.awt.Dimension(210, 15));
        lblBrandItem1.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem1.add(lblBrandItem1);
        lblBrandItem1.setBounds(0, 37, 210, 15);

        lblPriceItem1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPriceItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem1.setText("RM 100");
        lblPriceItem1.setMaximumSize(new java.awt.Dimension(210, 15));
        lblPriceItem1.setMinimumSize(new java.awt.Dimension(210, 15));
        lblPriceItem1.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem1.add(lblPriceItem1);
        lblPriceItem1.setBounds(0, 58, 210, 15);

        pnlItem1.add(pnlContentItem1);
        pnlContentItem1.setBounds(0, 105, 210, 105);

        add(pnlItem1);
        pnlItem1.setBounds(0, 0, 210, 210);

        pnlItem2.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem2.setMaximumSize(new java.awt.Dimension(210, 210));
        pnlItem2.setMinimumSize(new java.awt.Dimension(210, 210));
        pnlItem2.setPreferredSize(new java.awt.Dimension(210, 210));
        pnlItem2.setLayout(null);

        lblImageItem2.setMaximumSize(new java.awt.Dimension(210, 105));
        lblImageItem2.setMinimumSize(new java.awt.Dimension(210, 105));
        lblImageItem2.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlItem2.add(lblImageItem2);
        lblImageItem2.setBounds(0, 0, 210, 105);

        pnlContentItem2.setMaximumSize(new java.awt.Dimension(210, 105));
        pnlContentItem2.setMinimumSize(new java.awt.Dimension(210, 105));
        pnlContentItem2.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlContentItem2.setLayout(null);

        lblNameItem2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem2.setText("MR CHAIR");
        lblNameItem2.setMaximumSize(new java.awt.Dimension(210, 20));
        lblNameItem2.setMinimumSize(new java.awt.Dimension(210, 20));
        lblNameItem2.setPreferredSize(new java.awt.Dimension(210, 20));
        pnlContentItem2.add(lblNameItem2);
        lblNameItem2.setBounds(0, 11, 210, 20);

        lblBrandItem2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem2.setText("BRAND");
        lblBrandItem2.setMaximumSize(new java.awt.Dimension(210, 15));
        lblBrandItem2.setMinimumSize(new java.awt.Dimension(210, 15));
        lblBrandItem2.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem2.add(lblBrandItem2);
        lblBrandItem2.setBounds(0, 37, 210, 15);

        lblPriceItem2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPriceItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem2.setText("RM 100");
        lblPriceItem2.setMaximumSize(new java.awt.Dimension(210, 15));
        lblPriceItem2.setMinimumSize(new java.awt.Dimension(210, 15));
        lblPriceItem2.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem2.add(lblPriceItem2);
        lblPriceItem2.setBounds(0, 58, 210, 15);

        pnlItem2.add(pnlContentItem2);
        pnlContentItem2.setBounds(0, 105, 210, 105);

        add(pnlItem2);
        pnlItem2.setBounds(210, 0, 210, 210);

        pnlItem3.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem3.setMaximumSize(new java.awt.Dimension(210, 210));
        pnlItem3.setMinimumSize(new java.awt.Dimension(210, 210));
        pnlItem3.setPreferredSize(new java.awt.Dimension(210, 210));
        pnlItem3.setLayout(null);

        lblImageItem3.setMaximumSize(new java.awt.Dimension(210, 105));
        lblImageItem3.setMinimumSize(new java.awt.Dimension(210, 105));
        lblImageItem3.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlItem3.add(lblImageItem3);
        lblImageItem3.setBounds(0, 0, 210, 105);

        pnlContentItem3.setMaximumSize(new java.awt.Dimension(210, 105));
        pnlContentItem3.setMinimumSize(new java.awt.Dimension(210, 105));
        pnlContentItem3.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlContentItem3.setLayout(null);

        lblNameItem3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem3.setText("MR CHAIR");
        lblNameItem3.setMaximumSize(new java.awt.Dimension(210, 20));
        lblNameItem3.setMinimumSize(new java.awt.Dimension(210, 20));
        lblNameItem3.setPreferredSize(new java.awt.Dimension(210, 20));
        pnlContentItem3.add(lblNameItem3);
        lblNameItem3.setBounds(0, 11, 210, 20);

        lblBrandItem3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem3.setText("BRAND");
        lblBrandItem3.setMaximumSize(new java.awt.Dimension(210, 15));
        lblBrandItem3.setMinimumSize(new java.awt.Dimension(210, 15));
        lblBrandItem3.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem3.add(lblBrandItem3);
        lblBrandItem3.setBounds(0, 37, 210, 15);

        lblPriceItem3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPriceItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem3.setText("RM 100");
        lblPriceItem3.setMaximumSize(new java.awt.Dimension(210, 15));
        lblPriceItem3.setMinimumSize(new java.awt.Dimension(210, 15));
        lblPriceItem3.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem3.add(lblPriceItem3);
        lblPriceItem3.setBounds(0, 58, 210, 15);

        pnlItem3.add(pnlContentItem3);
        pnlContentItem3.setBounds(0, 105, 210, 105);

        add(pnlItem3);
        pnlItem3.setBounds(0, 210, 210, 210);

        pnlItem4.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem4.setMaximumSize(new java.awt.Dimension(210, 210));
        pnlItem4.setMinimumSize(new java.awt.Dimension(210, 210));
        pnlItem4.setPreferredSize(new java.awt.Dimension(210, 210));
        pnlItem4.setLayout(null);

        lblImageItem4.setMaximumSize(new java.awt.Dimension(210, 105));
        lblImageItem4.setMinimumSize(new java.awt.Dimension(210, 105));
        lblImageItem4.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlItem4.add(lblImageItem4);
        lblImageItem4.setBounds(0, 0, 210, 105);

        pnlContentItem4.setMaximumSize(new java.awt.Dimension(210, 105));
        pnlContentItem4.setMinimumSize(new java.awt.Dimension(210, 105));
        pnlContentItem4.setPreferredSize(new java.awt.Dimension(210, 105));
        pnlContentItem4.setLayout(null);

        lblNameItem4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem4.setText("MR CHAIR");
        lblNameItem4.setMaximumSize(new java.awt.Dimension(210, 20));
        lblNameItem4.setMinimumSize(new java.awt.Dimension(210, 20));
        lblNameItem4.setPreferredSize(new java.awt.Dimension(210, 20));
        pnlContentItem4.add(lblNameItem4);
        lblNameItem4.setBounds(0, 11, 210, 20);

        lblBrandItem4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem4.setText("BRAND");
        lblBrandItem4.setMaximumSize(new java.awt.Dimension(210, 15));
        lblBrandItem4.setMinimumSize(new java.awt.Dimension(210, 15));
        lblBrandItem4.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem4.add(lblBrandItem4);
        lblBrandItem4.setBounds(0, 37, 210, 15);

        lblPriceItem4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPriceItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem4.setText("RM 100");
        lblPriceItem4.setMaximumSize(new java.awt.Dimension(210, 15));
        lblPriceItem4.setMinimumSize(new java.awt.Dimension(210, 15));
        lblPriceItem4.setPreferredSize(new java.awt.Dimension(210, 15));
        pnlContentItem4.add(lblPriceItem4);
        lblPriceItem4.setBounds(0, 58, 210, 15);

        pnlItem4.add(pnlContentItem4);
        pnlContentItem4.setBounds(0, 105, 210, 105);

        add(pnlItem4);
        pnlItem4.setBounds(210, 210, 210, 210);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBrandItem1;
    private javax.swing.JLabel lblBrandItem2;
    private javax.swing.JLabel lblBrandItem3;
    private javax.swing.JLabel lblBrandItem4;
    private javax.swing.JLabel lblImageItem1;
    private javax.swing.JLabel lblImageItem2;
    private javax.swing.JLabel lblImageItem3;
    private javax.swing.JLabel lblImageItem4;
    private javax.swing.JLabel lblNameItem1;
    private javax.swing.JLabel lblNameItem2;
    private javax.swing.JLabel lblNameItem3;
    private javax.swing.JLabel lblNameItem4;
    private javax.swing.JLabel lblPriceItem1;
    private javax.swing.JLabel lblPriceItem2;
    private javax.swing.JLabel lblPriceItem3;
    private javax.swing.JLabel lblPriceItem4;
    private javax.swing.JPanel pnlContentItem1;
    private javax.swing.JPanel pnlContentItem2;
    private javax.swing.JPanel pnlContentItem3;
    private javax.swing.JPanel pnlContentItem4;
    private javax.swing.JPanel pnlItem1;
    private javax.swing.JPanel pnlItem2;
    private javax.swing.JPanel pnlItem3;
    private javax.swing.JPanel pnlItem4;
    // End of variables declaration//GEN-END:variables
}
