package productmanagement;

import java.awt.Image;
import java.nio.file.Paths;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTextArea;

public class ProductCatalogueThreeItemTemplate extends javax.swing.JPanel {
    ArrayList<ProductItem> items = new ArrayList<>();

    public ProductCatalogueThreeItemTemplate(String[] itemIds) {
        initComponents();
        
        // Get first three Items
        for (int i = 0; i < 3; i++) {
            boolean found = false;
            ArrayList<String> itemArray = ReadObject.readArray(ProductItem.FILE_NAME);
            // Iterate through the Item array
            for (String itemDetails : itemArray) {
                // Split the line into details
                String[] details = itemDetails.split(";");
                // Check the details for a matching Id
                if (details[0].equalsIgnoreCase(itemIds[i])) {
                    // Create a Product Item object and add into array list
                    items.add(new ProductItem(details));
                    found = true;
                    break;
                }
            }
            // If item is not found, create an empty Product Item object and add it to the array list
            if (!found) {
                items.add(new ProductItem("", "", "", 0, "", "", "", "", ""));
            }
        }

        resetItem(items.get(0), lblImageItem1, lblNameItem1, lblBrandItem1, lblPriceItem1, txaDescriptionItem1, 1);
        resetItem(items.get(1), lblImageItem2, lblNameItem2, lblBrandItem2, lblPriceItem2, txaDescriptionItem2, 2);
        resetItem(items.get(2), lblImageItem3, lblNameItem3, lblBrandItem3, lblPriceItem3, txaDescriptionItem3, 3);
    }

    private void resetItem(ProductItem item, JLabel lblImage, JLabel lblName, JLabel lblBrand, JLabel lblPrice, JTextArea txaDescription, int i) {
        if (!item.getItemId().trim().equalsIgnoreCase("")) {
            lblImage.setIcon(resizeImage(Paths.get("").toAbsolutePath().toString() + "/src" + item.getItemImagePath(), lblImage, i));
            lblName.setText(item.getItemName());
            lblBrand.setText(item.getItemBrand());
            lblPrice.setText("RM " + String.valueOf(item.getItemPrice()));
            txaDescription.setText(item.getItemDescription());
        } else {
            lblImage.setIcon(new ImageIcon());
            lblName.setText("Title");
            lblBrand.setText("Brand");
            lblPrice.setText("Price");
            txaDescription.setText("");
        }
    }
    
    // Create a method to resize the image and label
    private ImageIcon resizeImage(String imagePath, JLabel lblImage, int itemNo){
        int x, y;
        
        // Get the imageicon and get the width & height of the image
        ImageIcon MyImage = new ImageIcon(imagePath);
        x = MyImage.getIconWidth();
        y = MyImage.getIconHeight();
        
        // To differentiate the dimension of image (horizontal,vertical or square)
        // To resize the label based on the dimension
        // To relocate the picture to the right position based on the item number 
        if (x > y) {
            // If the width longer than height, then it is a horizontal image
                if(itemNo == 1){
                    lblImageItem1.setBounds(4,50,123,87);
                }else if(itemNo == 2){
                    lblImageItem2.setBounds(4,50,123,87);
                }else{
                    lblImageItem3.setBounds(4,50,123,87);
                }
                
        } else if (y > x){
            // If the height longer than width, then it is a vertical image
            if(itemNo == 1){
                lblImageItem1.setBounds(4,14,123,174);
            }else if(itemNo == 2){
                lblImageItem2.setBounds(4,14,123,174);
            }else{
                lblImageItem3.setBounds(4,14,123,174);
            }
                
        } else {
            // The width is equal to the height, then it is a square image
            if(itemNo == 1){
                lblImageItem1.setBounds(4,25,123,123);
            }else if(itemNo == 2){
                lblImageItem2.setBounds(4,25,123,123);
            }else{
                lblImageItem3.setBounds(4,25,123,123);
            }
        }
        
        // Resize the image to the size of the label
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance((int) lblImage.getPreferredSize().getWidth(),(int) lblImage.getPreferredSize().getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem1 = new javax.swing.JPanel();
        pnlContentItem1 = new javax.swing.JPanel();
        scrDescriptionItem1 = new javax.swing.JScrollPane();
        txaDescriptionItem1 = new javax.swing.JTextArea();
        lblBrandItem1 = new javax.swing.JLabel();
        lblPriceItem1 = new javax.swing.JLabel();
        lblNameItem1 = new javax.swing.JLabel();
        lblImageItem1 = new javax.swing.JLabel();
        pnlItem2 = new javax.swing.JPanel();
        pnlContentItem2 = new javax.swing.JPanel();
        scrDescriptionItem2 = new javax.swing.JScrollPane();
        txaDescriptionItem2 = new javax.swing.JTextArea();
        lblBrandItem2 = new javax.swing.JLabel();
        lblPriceItem2 = new javax.swing.JLabel();
        lblNameItem2 = new javax.swing.JLabel();
        lblImageItem2 = new javax.swing.JLabel();
        pnlItem3 = new javax.swing.JPanel();
        pnlContentItem3 = new javax.swing.JPanel();
        scrDescriptionItem3 = new javax.swing.JScrollPane();
        txaDescriptionItem3 = new javax.swing.JTextArea();
        lblBrandItem3 = new javax.swing.JLabel();
        lblPriceItem3 = new javax.swing.JLabel();
        lblNameItem3 = new javax.swing.JLabel();
        lblImageItem3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        pnlItem1.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem1.setLayout(null);

        scrDescriptionItem1.setBorder(null);
        scrDescriptionItem1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrDescriptionItem1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDescriptionItem1.setEditable(false);
        txaDescriptionItem1.setBackground(new java.awt.Color(240, 240, 240));
        txaDescriptionItem1.setColumns(20);
        txaDescriptionItem1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txaDescriptionItem1.setLineWrap(true);
        txaDescriptionItem1.setRows(5);
        txaDescriptionItem1.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry\n. Lorem Ipsum has been the industry's standard dummy text ever since t\nhe 1500s, when an unknown printer took a galley of type and scrambled it to m\nake a type specimen book. It has survived not only five centuries, but also the\n leap into electronic typesetting, remaining essentially unchanged. It was popula\nrised in the 1960s w");
        txaDescriptionItem1.setBorder(null);
        scrDescriptionItem1.setViewportView(txaDescriptionItem1);

        lblBrandItem1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem1.setText("BRAND");

        lblPriceItem1.setText("RM 100");

        lblNameItem1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem1.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem1Layout = new javax.swing.GroupLayout(pnlContentItem1);
        pnlContentItem1.setLayout(pnlContentItem1Layout);
        pnlContentItem1Layout.setHorizontalGroup(
            pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPriceItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameItem1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblBrandItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrDescriptionItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentItem1Layout.setVerticalGroup(
            pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDescriptionItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlItem1.add(pnlContentItem1);
        pnlContentItem1.setBounds(0, 200, 131, 201);

        lblImageItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lblImageItem1.setPreferredSize(new java.awt.Dimension(126, 178));
        pnlItem1.add(lblImageItem1);
        lblImageItem1.setBounds(4, 10, 123, 178);

        pnlItem2.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem2.setLayout(null);

        scrDescriptionItem2.setBorder(null);
        scrDescriptionItem2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrDescriptionItem2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDescriptionItem2.setEditable(false);
        txaDescriptionItem2.setBackground(new java.awt.Color(240, 240, 240));
        txaDescriptionItem2.setColumns(20);
        txaDescriptionItem2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txaDescriptionItem2.setLineWrap(true);
        txaDescriptionItem2.setRows(5);
        txaDescriptionItem2.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry\n. Lorem Ipsum has been the industry's standard dummy text ever since t\nhe 1500s, when an unknown printer took a galley of type and scrambled it to m\nake a type specimen book. It has survived not only five centuries, but also the\n leap into electronic typesetting, remaining essentially unchanged. It was popula\nrised in the 1960s w");
        txaDescriptionItem2.setBorder(null);
        scrDescriptionItem2.setViewportView(txaDescriptionItem2);

        lblBrandItem2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem2.setText("BRAND");

        lblPriceItem2.setText("RM 100");

        lblNameItem2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem2.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem2Layout = new javax.swing.GroupLayout(pnlContentItem2);
        pnlContentItem2.setLayout(pnlContentItem2Layout);
        pnlContentItem2Layout.setHorizontalGroup(
            pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPriceItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameItem2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblBrandItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrDescriptionItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentItem2Layout.setVerticalGroup(
            pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDescriptionItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pnlItem2.add(pnlContentItem2);
        pnlContentItem2.setBounds(0, 200, 131, 201);

        lblImageItem2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem2.add(lblImageItem2);
        lblImageItem2.setBounds(4, 10, 123, 180);

        pnlItem3.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem3.setLayout(null);

        scrDescriptionItem3.setBorder(null);
        scrDescriptionItem3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrDescriptionItem3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDescriptionItem3.setEditable(false);
        txaDescriptionItem3.setBackground(new java.awt.Color(240, 240, 240));
        txaDescriptionItem3.setColumns(20);
        txaDescriptionItem3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        txaDescriptionItem3.setLineWrap(true);
        txaDescriptionItem3.setRows(5);
        txaDescriptionItem3.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry\n. Lorem Ipsum has been the industry's standard dummy text ever since t\nhe 1500s, when an unknown printer took a galley of type and scrambled it to m\nake a type specimen book. It has survived not only five centuries, but also the\n leap into electronic typesetting, remaining essentially unchanged. It was popula\nrised in the 1960s w");
        txaDescriptionItem3.setBorder(null);
        scrDescriptionItem3.setViewportView(txaDescriptionItem3);

        lblBrandItem3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem3.setText("BRAND");

        lblPriceItem3.setText("RM 100");

        lblNameItem3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem3.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem3Layout = new javax.swing.GroupLayout(pnlContentItem3);
        pnlContentItem3.setLayout(pnlContentItem3Layout);
        pnlContentItem3Layout.setHorizontalGroup(
            pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPriceItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameItem3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(lblBrandItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrDescriptionItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentItem3Layout.setVerticalGroup(
            pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrDescriptionItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItem3.add(pnlContentItem3);
        pnlContentItem3.setBounds(0, 200, 131, 200);

        lblImageItem3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem3.add(lblImageItem3);
        lblImageItem3.setBounds(4, 10, 123, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(pnlItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pnlItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(pnlItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlItem2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(pnlItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBrandItem1;
    private javax.swing.JLabel lblBrandItem2;
    private javax.swing.JLabel lblBrandItem3;
    private javax.swing.JLabel lblImageItem1;
    private javax.swing.JLabel lblImageItem2;
    private javax.swing.JLabel lblImageItem3;
    private javax.swing.JLabel lblNameItem1;
    private javax.swing.JLabel lblNameItem2;
    private javax.swing.JLabel lblNameItem3;
    private javax.swing.JLabel lblPriceItem1;
    private javax.swing.JLabel lblPriceItem2;
    private javax.swing.JLabel lblPriceItem3;
    private javax.swing.JPanel pnlContentItem1;
    private javax.swing.JPanel pnlContentItem2;
    private javax.swing.JPanel pnlContentItem3;
    private javax.swing.JPanel pnlItem1;
    private javax.swing.JPanel pnlItem2;
    private javax.swing.JPanel pnlItem3;
    private javax.swing.JScrollPane scrDescriptionItem1;
    private javax.swing.JScrollPane scrDescriptionItem2;
    private javax.swing.JScrollPane scrDescriptionItem3;
    private javax.swing.JTextArea txaDescriptionItem1;
    private javax.swing.JTextArea txaDescriptionItem2;
    private javax.swing.JTextArea txaDescriptionItem3;
    // End of variables declaration//GEN-END:variables
}
