/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productmanagement;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author User
 */
public class ProductCatalogueFourItemTemplate extends javax.swing.JPanel {

    /**
     * Creates new form ProductCatalogueFourItemTemplate
     */
    public ProductCatalogueFourItemTemplate() {
        initComponents();
        
    }
    
    // Create a method to resize the image and label
    private ImageIcon resizeImage(String imagePath, JLabel lblImage, int itemNo){
        int x, y;
        
        // Get the imageicon and get the width & height of the image
        ImageIcon MyImage = new ImageIcon(imagePath);
        x = MyImage.getIconWidth();
        y = MyImage.getIconHeight();
        
        // To differentiate the dimension of image (horizontal,vertical or square)
        // To resize the label based on the dimension
        // To relocate the picture to the right position based on the item number
        if (x > y) {
            // If the width longer than height, then it is a horizontal image
            lblImage.setBounds(29,10,141,100);
                
        } else if (y > x){
            // If the height longer than width, then it is a vertical image
            lblImage.setBounds(70,10,71,100);
        } else {
            // The width is equal to the height, then it is a square image
            lblImage.setBounds(50,10,100,100);
        }
        
        // Resize the image to the size of the label
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance((int) lblImage.getPreferredSize().getWidth(),(int) lblImage.getPreferredSize().getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlItem1 = new javax.swing.JPanel();
        pnlContentItem1 = new javax.swing.JPanel();
        lblBrandItem1 = new javax.swing.JLabel();
        lblPriceItem1 = new javax.swing.JLabel();
        lblNameItem1 = new javax.swing.JLabel();
        lblImageItem1 = new javax.swing.JLabel();
        pnlItem2 = new javax.swing.JPanel();
        pnlContentItem2 = new javax.swing.JPanel();
        lblBrandItem2 = new javax.swing.JLabel();
        lblPriceItem2 = new javax.swing.JLabel();
        lblNameItem2 = new javax.swing.JLabel();
        lblImageItem2 = new javax.swing.JLabel();
        pnlItem3 = new javax.swing.JPanel();
        pnlContentItem3 = new javax.swing.JPanel();
        lblBrandItem3 = new javax.swing.JLabel();
        lblPriceItem3 = new javax.swing.JLabel();
        lblNameItem3 = new javax.swing.JLabel();
        lblImageItem3 = new javax.swing.JLabel();
        pnlItem4 = new javax.swing.JPanel();
        pnlContentItem4 = new javax.swing.JPanel();
        lblBrandItem4 = new javax.swing.JLabel();
        lblPriceItem4 = new javax.swing.JLabel();
        lblNameItem4 = new javax.swing.JLabel();
        lblImageItem4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        pnlItem1.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem1.setPreferredSize(new java.awt.Dimension(200, 198));
        pnlItem1.setLayout(null);

        lblBrandItem1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem1.setText("BRAND");

        lblPriceItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem1.setText("RM 100");

        lblNameItem1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem1.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem1Layout = new javax.swing.GroupLayout(pnlContentItem1);
        pnlContentItem1.setLayout(pnlContentItem1Layout);
        pnlContentItem1Layout.setHorizontalGroup(
            pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrandItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlContentItem1Layout.setVerticalGroup(
            pnlContentItem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItem1.add(pnlContentItem1);
        pnlContentItem1.setBounds(0, 120, 200, 78);

        lblImageItem1.setText("Image");
        lblImageItem1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem1.add(lblImageItem1);
        lblImageItem1.setBounds(29, 10, 141, 100);

        pnlItem2.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem2.setPreferredSize(new java.awt.Dimension(200, 198));
        pnlItem2.setLayout(null);

        lblBrandItem2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem2.setText("BRAND");

        lblPriceItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem2.setText("RM 100");

        lblNameItem2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem2.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem2Layout = new javax.swing.GroupLayout(pnlContentItem2);
        pnlContentItem2.setLayout(pnlContentItem2Layout);
        pnlContentItem2Layout.setHorizontalGroup(
            pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrandItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceItem2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlContentItem2Layout.setVerticalGroup(
            pnlContentItem2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItem2.add(pnlContentItem2);
        pnlContentItem2.setBounds(0, 120, 200, 78);

        lblImageItem2.setText("Image");
        lblImageItem2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem2.add(lblImageItem2);
        lblImageItem2.setBounds(29, 10, 141, 100);

        pnlItem3.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem3.setPreferredSize(new java.awt.Dimension(200, 198));
        pnlItem3.setLayout(null);

        lblBrandItem3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem3.setText("BRAND");

        lblPriceItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem3.setText("RM 100");

        lblNameItem3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem3.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem3Layout = new javax.swing.GroupLayout(pnlContentItem3);
        pnlContentItem3.setLayout(pnlContentItem3Layout);
        pnlContentItem3Layout.setHorizontalGroup(
            pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrandItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceItem3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlContentItem3Layout.setVerticalGroup(
            pnlContentItem3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItem3.add(pnlContentItem3);
        pnlContentItem3.setBounds(0, 120, 200, 78);

        lblImageItem3.setText("Image");
        lblImageItem3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem3.add(lblImageItem3);
        lblImageItem3.setBounds(29, 10, 141, 100);

        pnlItem4.setBackground(new java.awt.Color(255, 255, 255));
        pnlItem4.setPreferredSize(new java.awt.Dimension(200, 198));
        pnlItem4.setLayout(null);

        lblBrandItem4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrandItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandItem4.setText("BRAND");

        lblPriceItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPriceItem4.setText("RM 100");

        lblNameItem4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        lblNameItem4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameItem4.setText("MR CHAIR");

        javax.swing.GroupLayout pnlContentItem4Layout = new javax.swing.GroupLayout(pnlContentItem4);
        pnlContentItem4.setLayout(pnlContentItem4Layout);
        pnlContentItem4Layout.setHorizontalGroup(
            pnlContentItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlContentItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameItem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBrandItem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceItem4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlContentItem4Layout.setVerticalGroup(
            pnlContentItem4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentItem4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNameItem4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBrandItem4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPriceItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItem4.add(pnlContentItem4);
        pnlContentItem4.setBounds(0, 120, 200, 78);

        lblImageItem4.setText("Image");
        lblImageItem4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlItem4.add(lblImageItem4);
        lblImageItem4.setBounds(29, 10, 141, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(pnlItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(pnlItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlItem3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlItem4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBrandItem1;
    private javax.swing.JLabel lblBrandItem2;
    private javax.swing.JLabel lblBrandItem3;
    private javax.swing.JLabel lblBrandItem4;
    private javax.swing.JLabel lblImageItem1;
    private javax.swing.JLabel lblImageItem2;
    private javax.swing.JLabel lblImageItem3;
    private javax.swing.JLabel lblImageItem4;
    private javax.swing.JLabel lblNameItem1;
    private javax.swing.JLabel lblNameItem2;
    private javax.swing.JLabel lblNameItem3;
    private javax.swing.JLabel lblNameItem4;
    private javax.swing.JLabel lblPriceItem1;
    private javax.swing.JLabel lblPriceItem2;
    private javax.swing.JLabel lblPriceItem3;
    private javax.swing.JLabel lblPriceItem4;
    private javax.swing.JPanel pnlContentItem1;
    private javax.swing.JPanel pnlContentItem2;
    private javax.swing.JPanel pnlContentItem3;
    private javax.swing.JPanel pnlContentItem4;
    private javax.swing.JPanel pnlItem1;
    private javax.swing.JPanel pnlItem2;
    private javax.swing.JPanel pnlItem3;
    private javax.swing.JPanel pnlItem4;
    // End of variables declaration//GEN-END:variables
}
