package productmanagement;

import java.awt.Image;
import java.nio.file.Paths;
import java.util.ArrayList;

import javax.swing.ImageIcon;

public class ProductCatalogueOneItemTemplate extends javax.swing.JPanel {
    private ProductItem item;
    
    public ProductCatalogueOneItemTemplate(String[] itemIds) {
        initComponents();
        
        if (!itemIds[0].trim().equalsIgnoreCase("")) {
            ArrayList<String> itemArray = ReadObject.readArray(ProductItem.FILE_NAME);
            for (String itemDetails : itemArray) {
                String[] details = itemDetails.split(";");
                if (details[0].equalsIgnoreCase(itemIds[0])) {
                    item = new ProductItem(details);
                }
            }

            lblImage.setIcon(resizeImage(Paths.get("").toAbsolutePath().toString() + "/src" + item.getItemImagePath()));
            lblTitle.setText(item.getItemName());
            lblBrand.setText(item.getItemBrand());
            lblPrice.setText("RM " + String.valueOf(item.getItemPrice()));
            txaDescription.setText(item.getItemDescription());
        } else {
            lblImage.setIcon(new ImageIcon());
            lblTitle.setText("Title");
            lblBrand.setText("Brand");
            lblPrice.setText("Price");
            txaDescription.setText("");
        }

        lblImage.setLocation(lblImage.getBounds().x, lblImage.getBounds().y);
    }
    
       
    // Create a method to resize the image and label
    private ImageIcon resizeImage(String imagePath){
        int x, y;
        double width, height, ratio;
        width = lblImage.getPreferredSize().getWidth();
        height = lblImage.getPreferredSize().getHeight();

        // Get the imageicon and get the width & height of the image
        ImageIcon MyImage = new ImageIcon(imagePath);
        x = MyImage.getIconWidth();
        y = MyImage.getIconHeight();
        ratio = (double) x / y;
        
        // To differentiate if the image is wider or higher than the label
        if (ratio > (width / height)) {
            if (ratio >= 1) {
                lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y + (int) Math.round((height - (height / ratio)) / 2), (int) width, (int) Math.round(height / ratio));
            } else {
                lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y + (int) Math.round((height - (height * ratio)) / 2), (int) width, (int) Math.round(height * ratio));
            }
        } else if (ratio < (width / height)){
            if (ratio >= 1) {
                lblImage.setBounds(lblImage.getBounds().x + (int) Math.round((width - (height / ratio)) / 2), lblImage.getBounds().y, (int) Math.round(height / ratio), (int) height);
            } else {
                lblImage.setBounds(lblImage.getBounds().x + (int) Math.round((width - (height * ratio)) / 2), lblImage.getBounds().y, (int) Math.round(height * ratio), (int) height);
            }
        } else {
            // The width is equal to the height, then only scale the image
            lblImage.setBounds(lblImage.getBounds().x, lblImage.getBounds().y, (int) width, (int) height);
        }
        
        // Resize the image to the size of the label
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance((int) lblImage.getBounds().getWidth(),(int) lblImage.getBounds().getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        scrDescription = new javax.swing.JScrollPane();
        txaDescription = new javax.swing.JTextArea();
        pnlImage = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(420, 420));
        setMinimumSize(new java.awt.Dimension(420, 420));
        setPreferredSize(new java.awt.Dimension(420, 420));
        setLayout(null);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setPreferredSize(new java.awt.Dimension(420, 220));
        pnlContent.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblTitle.setText("MR CHAIR");
        lblTitle.setPreferredSize(new java.awt.Dimension(410, 21));
        pnlContent.add(lblTitle);
        lblTitle.setBounds(10, 11, 400, 21);

        lblBrand.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblBrand.setText("BRAND");
        lblBrand.setPreferredSize(new java.awt.Dimension(410, 13));
        pnlContent.add(lblBrand);
        lblBrand.setBounds(10, 38, 400, 13);

        lblPrice.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lblPrice.setText("RM 100");
        lblPrice.setPreferredSize(new java.awt.Dimension(410, 14));
        pnlContent.add(lblPrice);
        lblPrice.setBounds(10, 57, 400, 14);

        scrDescription.setBorder(null);
        scrDescription.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrDescription.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrDescription.setMaximumSize(new java.awt.Dimension(400, 127));
        scrDescription.setMinimumSize(new java.awt.Dimension(400, 127));
        scrDescription.setPreferredSize(new java.awt.Dimension(400, 127));
        scrDescription.setLayout(null);

        txaDescription.setEditable(false);
        txaDescription.setColumns(20);
        txaDescription.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txaDescription.setLineWrap(true);
        txaDescription.setRows(5);
        txaDescription.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an nknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typeseting, remaining essentially unchanged. It was popularised in the 1960s w");
        txaDescription.setBorder(null);
        txaDescription.setMaximumSize(new java.awt.Dimension(400, 127));
        txaDescription.setMinimumSize(new java.awt.Dimension(400, 127));
        txaDescription.setPreferredSize(new java.awt.Dimension(400, 127));
        scrDescription.setViewportView(txaDescription);
        scrDescription.add(txaDescription);
        txaDescription.setBounds(0, 0, 400, 127);

        pnlContent.add(scrDescription);
        scrDescription.setBounds(10, 82, 400, 127);

        add(pnlContent);
        pnlContent.setBounds(0, 200, 420, 220);

        pnlImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlImage.setMaximumSize(new java.awt.Dimension(420, 200));
        pnlImage.setMinimumSize(new java.awt.Dimension(420, 200));
        pnlImage.setPreferredSize(new java.awt.Dimension(420, 200));
        pnlImage.setLayout(null);

        lblImage.setMaximumSize(new java.awt.Dimension(420, 200));
        lblImage.setMinimumSize(new java.awt.Dimension(420, 200));
        lblImage.setPreferredSize(new java.awt.Dimension(420, 200));
        pnlImage.add(lblImage);
        lblImage.setBounds(0, 0, 420, 200);

        add(pnlImage);
        pnlImage.setBounds(0, 0, 420, 200);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JScrollPane scrDescription;
    private javax.swing.JTextArea txaDescription;
    // End of variables declaration//GEN-END:variables
}
